name: Build and deploy functions
run-name: Build and deploy functions 🚀
'on':
  push:
    branches:
      - chore/functions-setup
jobs:
  Build-Deploy-Functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: ./functions
        run: |
          npm ci
          npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}